{% set name = "pydalle" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydalle-{{ version }}.tar.gz
  sha256: ef63a0ada8e9d44d8cdecefaee7efd89902ad92802e708fdcc838733de3b4d63

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
  run:
    - python >={{ python_min }}

test:
  imports:
    - pydalle
    - pydalle.functional
    - pydalle.functional.api
    - pydalle.functional.api.flow
    - pydalle.functional.api.request
    - pydalle.functional.api.response
    - pydalle.imperative
    - pydalle.imperative.api
    - pydalle.imperative.client
    - pydalle.imperative.outside
  commands:
    - pip check
  requires:
    - aiofiles
    - aiohttp
    - numpy
    - pillow
    - pip
    - requests
    - python {{ python_min }}

about:
  home: https://github.com/nottheswimmer/dalle
  doc_url: https://pydalle.readthedocs.io/en/latest/
  summary: A library for providing programmatic access to the DALL E 2 API
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
